## joint_names
joint_names: [simple_gripper_gripper_finger1_joint]

# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - simple_gripper_gripper_finger1_joint

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - simple_gripper_gripper_finger1_joint

  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      simple_gripper_gripper_finger1_joint : {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7


## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - simple_gripper_gripper_finger1_joint
  required_drive_mode: 1

simple_gripper_gripper_finger1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: simple_gripper_gripper_finger1_joint
  required_drive_mode: 1
